codecov:
  branch: master

coverage:
  range: 50...100

  status:
    project:
      enabled: yes
      target: 80%
    patch:
      enabled: yes
      target: 80%
      if_no_uploads: error
      if_not_found: success
    changes: false

comment:
  layout: "header, diff"
behavior: default
