from ttkwidgets.entries.scaleentry import ScaleEntry
from ttkwidgets.entries.keybindingentry import KeybindingEntry
from ttkwidgets.entries.placeholderentry import PlaceholderEntry
from ttkwidgets.entries.selectfolderentry import SelectFolderEntry
